<?php


/**
 * Implements hook_menu().
 */
function lfjs_example_menu() {
  $items['example'] = array(
    'title' => 'Example map',
    'page callback' => '_example',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );
  return $items;
}

function _example() {
  $build = array(
    'map' => array(
      '#markup' => '<div id="map-example"></div>',
    ),
  );

  drupal_add_js(drupal_get_path('module', 'lfjs_example') . '/lfjs_example.js');
  drupal_add_css(drupal_get_path('module', 'lfjs_example') . '/lfjs_example.css');

  // Add leaflet library.
  libraries_load('leaflet');


  return $build;
}


